[package]
name = "bft-wal"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
bincode = "0.8.0"
authority_manage = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
