language: generic
sudo: required
cache:
  timeout: 600
  directories:
  - $HOME/.docker_cargo
  - $TRAVIS_BUILD_DIR/target
services:
  - docker
jobs:
  include:
    - stage: Build & Test
      script:
        - docker pull cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
        - ./env.sh ./scripts/ci.sh
