version: 2
jobs:
  build_sha3:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - checkout
      - run:
          name: checkout_submodule
          command: 'git submodule update --init'
      - run:
          name: format
          command: 'echo $CARGO_HOME; cargo fmt --all  -- --check'
      - run:
          name: build
          command: 'RUSTFLAGS="-F warnings" cargo build --all'
          no_output_timeout: 20m
      - run:
          name: check_cargolock
          command: '[ $(git status --short Cargo.lock | wc -l) -ne 0 ] && echo "[Error] Please update Cargo.lock BEFORE commit." && git diff Cargo.lock && exit 1 || true'
      - run:
          name: security_audit
          command: 'make security_audit'
      - save_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
          paths:
            - ~/cita-build
      - save_cache:
          key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
          paths:
            - /opt/.cargo

  basic_test_sha3:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
      - restore_cache:
          key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
      - run:
          name: test
          command: 'RUSTFLAGS="-F warnings" cargo test --tests'

  build_blake2b:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
      - restore_cache:
          key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
      - run:
          name: replace_hash
          command: ./scripts/replace_default_feature.sh ./ sha3hash blake2bhash
      - run:
          name: replace_crypt
          command: ./scripts/replace_default_feature.sh ./ secp256k1 ed25519
      - run:
          name: build
          command: 'RUSTFLAGS="-F warnings" cargo build --all'
          no_output_timeout: 20m
      - save_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-blake2b
          paths:
            - ~/cita-build
      - save_cache:
          key: v2-deps-{{ checksum "Cargo.lock" }}-blake2b
          paths:
            - /opt/.cargo

  basic_test_blake2b:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-blake2b
      - restore_cache:
          key: v2-deps-{{ checksum "Cargo.lock" }}-blake2b
      - run:
          name: test
          command: 'RUSTFLAGS="-F warnings" cargo test --tests'

  # basic_test_coverage_sha3:
  #   docker:
  #     - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
  #   working_directory: ~/cita-build
  #   resource_class: large
  #   steps:
  #     - restore_cache:
  #         key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
  #     - restore_cache:
  #         key: v2-deps-{{ checksum "Cargo.lock" }}-sha3
  #     - run:
  #         name: test-coverage
  #         command: |
  #           bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  #           cargo tarpaulin \
  #             --packages cita-auth \
  #             --packages cita-jsonrpc \
  #             --packages cita-chain \
  #             --packages core \
  #             --packages common-types \
  #             --packages cita-bft \
  #             --packages cita-network \
  #             --packages cita-executor \
  #             --packages core-executor \
  #             --packages cita-forever \
  #             --packages jsonrpc_types \
  #             --skip-clean --coveralls ${COVERALLS_TOKEN}

  integrate_test_sha3:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
      - run:
          name: config
          command: './scripts/release.sh debug'
      - run:
          name: basic
          command: './tests/integrate_test/cita_basic.sh'
      - run:
          # EconomicalModel == Quota
          name: byzantine-quota
          command: './tests/integrate_test/cita_byzantinetest.sh quota'
      - run:
          # EconomicalModel == Charge
          name: byzantine-charge
          command: './tests/integrate_test/cita_byzantinetest.sh charge'
      - run:
          # EconomicalModel == Quota
          name: jsonrpc-mock-tests-quota
          command: './tests/integrate_test/cita_jsonrpc_schema_mock.sh quota'
      # TODO: We should add it back later
      # - run:
          # EconomicalModel == Charge
          # name: jsonrpc-mock-tests-charge
          # command: './tests/integrate_test/cita_jsonrpc_schema_mock.sh charge'
      - run:
          name: economical-mode-charge-transfer-value
          command: './tests/integrate_test/cita_charge_mode.sh'

  integrate_test_crosschain_sha3:
    docker:
      - image: cita/cita-build:ubuntu-18.04-20180703-solc-0.4.15-s17
    working_directory: ~/cita-build
    resource_class: large
    steps:
      - restore_cache:
          key: v2-cita-build-{{ .Environment.CIRCLE_SHA1 }}-sha3
      - run:
          name: config
          command: './scripts/release.sh debug'
      - run:
          name: crosschain
          command: './tests/integrate_test/cita_crosschain.sh'

workflows:
  version: 2
  build-and-test:
    jobs:
      - build_sha3
      - build_blake2b:
          requires:
            - basic_test_sha3
      - basic_test_sha3:
          requires:
            - build_sha3
      # - basic_test_coverage_sha3:
      #     requires:
      #       - build_sha3
      - integrate_test_sha3:
          requires:
            - build_sha3
      - integrate_test_crosschain_sha3:
          requires:
            - build_sha3
      - basic_test_blake2b:
          requires:
            - build_blake2b
