[package]
name = "cita-executor"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]

[dependencies]
dotenv = "0.13.0"
clap = "2"
serde_json = "1.0"
grpc = "0.5.0"
cita-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
logger = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
pubsub = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
libproto = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
error =  { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
proof = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }
core-executor = { path = "./core" }
common-types = { path = "../cita-chain/types" }
jsonrpc-types = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }

[build-dependencies]
util = { git = "https://github.com/cryptape/cita-common.git", branch = "develop" }


[features]
default = ["secp256k1", "sha3hash", "rabbitmq"]
secp256k1 = ["libproto/secp256k1", "proof/secp256k1", "jsonrpc-types/secp256k1"]
ed25519 = ["libproto/ed25519", "proof/ed25519", "jsonrpc-types/ed25519"]
sm2 = ["libproto/sm2", "proof/sm2", "jsonrpc-types/sm2"]
sha3hash = ["util/sha3hash", "libproto/sha3hash", "proof/sha3hash", "jsonrpc-types/sha3hash"]
blake2bhash = ["util/blake2bhash", "libproto/blake2bhash", "proof/blake2bhash", "jsonrpc-types/blake2bhash"]
sm3hash = ["util/sm3hash", "libproto/sm3hash", "proof/sm3hash", "jsonrpc-types/sm3hash"]
rabbitmq = ["pubsub/rabbitmq"]
zeromq = ["pubsub/zeromq"]
kafka = ["pubsub/kafka"]
privatetx = ["core-executor/privatetx"]
evm-debug = ["core-executor/evm-debug"]
evm-debug-tests = ["evm-debug", "core-executor/evm-debug-tests"]
